task_0:
 video_path: "data/video/train_video1.mp4"
 audio_path: "data/audio/train_video1.wav"

task_1:
 video_path: "data/video/train_video2.mp4"
 audio_path: "data/audio/train_video2.wav"
 bbox_shift: -7
  

